site_name: C0d3
repo_name: byc0d3/code
site_url: https://byc0d3.github.io/code/

theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: blue
  logo: assets/debian.svg
  favicon: assets/favicon.ico
  features:
    - navigation.footer

plugins:
  - search

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
extra_css:
  - assets/styles.css
extra:
  generator: false
  social:
    - icon: simple/youtube
      link: https://youtube.com/@james-willett
    - icon: material/linkedin
      link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2026 byc0d3
